/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_inscription1 (void);
GtkWidget* create_acceuil_don (void);
GtkWidget* create_ajoute_don (void);
GtkWidget* create_modifer_don (void);
GtkWidget* create_supprim_don (void);
GtkWidget* create_quantite_sang (void);
